In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('harmful_ingredients_real_products.csv')
df

Product Name  \
0                Cup Noodles   
1        Listerine Mouthwash   
2           L'Oreal Hair Dye   
3        Old Spice Deodorant   
4      Red Bull Energy Drink   
..                       ...   
195    Red Bull Energy Drink   
196         Nivea Face Cream   
197      Chanel No.5 Perfume   
198  Herbal Essences Shampoo   
199         Nivea Face Cream   

                                   Harmful Ingredients  
0                       Lead, Butylated Hydroxyanisole  
1         Synthetic Musks, Microplastics, Hydroquinone  
2               BHT, Artificial Preservatives, Mercury  
3    Oxybenzone, PPD (Para-phenylenediamine), Sulfa...  
4               MSG, Codeine, High Fructose Corn Syrup  
..                                                 ...  
195                       Toluene, Polyethylene Glycol  
196          Synthetic Musks, Butylated Hydroxyanisole  
197      Aspartame, Fluoride, Artificial Preservatives  
198                        Phthalates, Petroleum Jelly  
199                         BHA, Formaldehyde, Codeine  

[200 rows x 2 columns]

In [ ]:
df.info


<bound method DataFrame.info of                 Product Name  \
0                Cup Noodles   
1        Listerine Mouthwash   
2           L'Oreal Hair Dye   
3        Old Spice Deodorant   
4      Red Bull Energy Drink   
..                       ...   
195    Red Bull Energy Drink   
196         Nivea Face Cream   
197      Chanel No.5 Perfume   
198  Herbal Essences Shampoo   
199         Nivea Face Cream   

                                   Harmful Ingredients  
0                       Lead, Butylated Hydroxyanisole  
1         Synthetic Musks, Microplastics, Hydroquinone  
2               BHT, Artificial Preservatives, Mercury  
3    Oxybenzone, PPD (Para-phenylenediamine), Sulfa...  
4               MSG, Codeine, High Fructose Corn Syrup  
..                                                 ...  
195                       Toluene, Polyethylene Glycol  
196          Synthetic Musks, Butylated Hydroxyanisole  
197      Aspartame, Fluoride, Artificial Preservatives  
198                        Phthalates, Petroleum Jelly  
199                         BHA, Formaldehyde, Codeine  

[200 rows x 2 columns]>

In [ ]:
import sklearn.feature_extraction

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

When you use a vector that convert words based don importance that we should pass to a variable and then use as tfid passed into vector

In [ ]:
X =df['Product Name']
y = df['Harmful Ingredients']

In [ ]:
vector = TfidfVectorizer()

X_harm=vector.fit_transform(X)

In [ ]:
print(X_harm.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(y)

0                         Lead, Butylated Hydroxyanisole
1           Synthetic Musks, Microplastics, Hydroquinone
2                 BHT, Artificial Preservatives, Mercury
3      Oxybenzone, PPD (Para-phenylenediamine), Sulfa...
4                 MSG, Codeine, High Fructose Corn Syrup
                             ...                        
195                         Toluene, Polyethylene Glycol
196            Synthetic Musks, Butylated Hydroxyanisole
197        Aspartame, Fluoride, Artificial Preservatives
198                          Phthalates, Petroleum Jelly
199                           BHA, Formaldehyde, Codeine
Name: Harmful Ingredients, Length: 200, dtype: object


In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

In [ ]:
multi = MultiLabelBinarizer()

In [ ]:
y_harm = multi.fit_transform(y)

In [ ]:
print(y_harm)

[[1 0 0 ... 1 1 0]
 [1 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]]


In [ ]:
res = pd.DataFrame(y, columns=multi.classes_)
res

Empty DataFrame
Columns: [ , (, ), ,, -, A, B, C, D, F, G, H, J, L, M, O, P, S, T, a, b, c, d, e, f, g, h, i, k, l, m, n, o, p, q, r, s, t, u, v, x, y, z]
Index: []

[0 rows x 43 columns]